### ISSUE TITLE
edp.update and epd.partial_update algorithms

### ISSUE THREAD

**Issue by viper4049** [repaper/gratis#19]
When doing an epd.update on the 2.7" display, the full refresh takes over 3 seconds (first showing inverted image, then flashing a number of times).  Is there any way to change this algorithm for a faster refresh?

Also, what is the difference in epd.partial_update? (I can't notice any)  Say, for example, I only want to refresh the top half of the display - is there any way to do this (while keeping the bottom static/not flashing)?

**Comment by CharmingSu** [comment]
New V231 display with G2 driver are available in March 2015 on Digi-Key!

- 1.44": [E1144CS021](http://www.digikey.com/product-detail/en/E1144CS021/E1144CS021-ND/5046789)
- 1.9" : [E1190CS021](http://www.digikey.com/product-detail/en/E1190CS021/E1190CS021-ND/5046790)
- 2.0" : [E1200CS021](http://www.digikey.com/product-detail/en/E1200CS021/E1200CS021-ND/5046791)
- 2.6" : [E1260CS021](http://www.digikey.com/product-detail/en/E1260CS021/E1260CS021-ND/5046792)
- 2.7" : [E1270CS021](http://www.digikey.com/product-detail/en/E1270CS021/E1270CS021-ND/5046793)

The Gratis Github code is upgrading.

For more information of the difference, please visit [Pervasive Displays](http://www.pervasivedisplays.com/products/panels#tab2).
How to identify your display type, please check the rear label of your display by [this link](http://www.pervasivedisplays.com/products/label_info). 

By FAE - Charming Su of Pervasive Displays

**Comment by viper4049** [comment]
Will these new displays still work with the SM027 development board?

Please let me know when the Github code is upgraded.  Thanks!

**Comment by CharmingSu** [comment]
Yes. The board(driving circuit) is compatible with all the displays (forward & backward), just the firmware code needs to be revised.

**Comment by phlips** [comment]
Which files and parts do I have to edit for implementing partial update?

**Comment by hxw** [comment]
fix has been merged
