### ISSUE TITLE
Unsupported EPD FLASH chip

### ISSUE THREAD

**Issue by Knowlue** [repaper/gratis#44]
unsupported EPD FLASH chip: MFG: 0x0  device: 0x0. I'm getting the following error when trying to run the demo code with an Arduino UNO and 2" display. It is also displaying a temperature of 117 Celcius which seems highly unlikely

**Comment by hxw** [comment]
all zero values are indication of some SPI problem.  Temperature would be floating ADC input.  Would you double check the connections.

**Comment by Knowlue** [comment]
Hey man, yeah some connections were wrong in the end and that fixed it, thanks!
