### ISSUE TITLE
Error in epd-fuse.service

### ISSUE THREAD

**Issue by NicolaP8** [repaper/gratis#53]
Hi,
the file epd-fuse.service contains at line 13:
`ExecStartPre=/usr/bin/mkdir -p ${EPD_MOUNTPOINT}`
but this is wrong because you can never be sure of the position of mkdir (in my system is /bin). For this exists the PATH.

**Comment by hxw** [comment]
Problem is that systemd seem to require absolute paths for the executable files :(
```
[/usr/lib/systemd/system/epd-fuse.service:13] Executable path is not absolute, ignoring: mkdir -p ${EPD_MOUNTPOINT}
```

**Comment by hxw** [comment]
Maybe the best solution is to try to detect the programs during make install and used sed to modify the service file.  Any better solutions?

**Comment by francesco-vannini** [comment]
We are also are seeing the same issue.
