### ISSUE TITLE
Do we need a terminating '\n' in the error strings (/dev/epd/error)?

### ISSUE THREAD

**Issue by tvoverbeek** [repaper/gratis#66]
In the recent addition of /dev/epd/error in epd_fuse.c the strings representing the error codes (output of 'cat /dev/epd/error') do not have a terminating '\n'. Other strings, e.g. /dev/epd/panel and /dev/epd/version, have a terminating '\n'.
Should a '\n' be added to the error text definitions?

**Comment by hxw** [comment]
actual error text definitions should not have any '\n' but the the access to /dev/epd/error should output a '\n' to conform to other usage.

**Comment by tvoverbeek** [comment]
The error text definitions are only used for /dev/epd/error output. I'll add the '\n' and submit a new PR.

**Comment by tvoverbeek** [comment]
Just submitted a PR (#67) with the '\n' addition to the error texts.

**Comment by tvoverbeek** [comment]
PR is merged now. Closing issue
