### ISSUE TITLE
E2271CS021 stm32 driver support

### ISSUE THREAD

**Issue by KiranKanchi** [repaper/gratis#83]
Does anybody successful interfaced E2271CS021 with stm32?

**Comment by Hardy-PDi** [comment]
Hello KiranKanchi,
Please find the link below,
https://bitbucket.org/mrazekv/stm32f4-epd-eink/overview

**Comment by KiranKanchi** [comment]
Wow! Thank you very much .
You saved my day :-)

Regards
Kiran Kanchi

**Comment by KiranKanchi** [comment]
i have a CY8CKIT-028-EPD which has E2271CS021 only, no SPI memory on the shield.
the code does not seem to work with it. i commented out all the stuff related to memory though.

Anybody have tried to use the cypress kit, perhaps with arduino /

**Comment by Hardy-PDi** [comment]
Hello KiranKanchi,
Pleas check this link out
https://iotexpert.com/2019/04/15/cy8ckit-028-epd-and-modus-toolbox-1-1/
